### ISSUE TITLE
addon.py

### ISSUE THREAD

**Issue by LuvSheRyL** [fuckwonderfulsuccess/WCplus#2]
Addon error: Traceback (most recent call last):
  File "..\WCplus\cmp\proxy_server\addons.py", line 59, in response
    text_dict = json.loads(text)
  File "..\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "..\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "..\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by LuvSheRyL** [comment]
| cmp.proxy_server.addons:response:59 - {"ret":0,"errmsg":"ok","cookie_count":0,"base_resp":{"ret":0,"errmsg":"ok","cookie_count":0,"sessionid":"svr_9d24fa5747e"},"sessionid":"svr_9d24fa5747e"}
Addon error: Traceback (most recent call last):
  File "..\WCplus\cmp\proxy_server\addons.py", line 70, in response
    current_nickname = html_text.split('var nickname = "')[1].split('" || ""')[0]
IndexError: list index out of range

**Comment by 40740** [comment]
你那边有这个问题吗？raise ValueError('Invalid async_mode specified')
ValueError: Invalid async_mode specified

**Comment by LuvSheRyL** [comment]
> 你那边有这个问题吗？raise ValueError('Invalid async_mode specified')
> ValueError: Invalid async_mode specified

解决了，删掉gevent那个参数。

**Comment by 40740** [comment]
厉害，解决了，不过发现新的问题。
from wsproto.connection import ConnectionType, WSConnection
ImportError: cannot import name 'WSConnection'

bug多多

**Comment by honglingjiner** [comment]
兄弟 有QQ群或者微信群可以加一下讨论一下嘛

**Comment by 40740** [comment]
> 兄弟 有QQ群或者微信群可以加一下讨论一下嘛

你这么一说 提醒我了。我刚刚建了一个。qun号 942782482   一起来解决bug

**Comment by 40740** [comment]
> 兄弟 有QQ群或者微信群可以加一下讨论一下嘛
来，刚刚弄了一个，来解决bug
（虽然只有我一个人哈哈哈）
http://shang.qq.com/wpa/qunwpa?idkey=c683813ad353fd81649b646dc73a4b5613361da39fcef6794c4f78e6231adceb

**Comment by aipracticer** [comment]
> | cmp.proxy_server.addons:response:59 - {"ret":0,"errmsg":"ok","cookie_count":0,"base_resp":{"ret":0,"errmsg":"ok","cookie_count":0,"sessionid":"svr_9d24fa5747e"},"sessionid":"svr_9d24fa5747e"}
> Addon error: Traceback (most recent call last):
> File "..\WCplus\cmp\proxy_server\addons.py", line 70, in response
> current_nickname = html_text.split('var nickname = "')[1].split('" || ""')[0]
> IndexError: list index out of range
哥们 这个问题解决了吗？

**Comment by yichengye310** [comment]
> Addon error: Traceback (most recent call last):
> File "..\WCplus\cmp\proxy_server\addons.py", line 59, in response
> text_dict = json.loads(text)
> File "..\Python37\lib\json__init__.py", line 348, in loads
> return _default_decoder.decode(s)
> File "..\lib\json\decoder.py", line 337, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "..\Python37\lib\json\decoder.py", line 355, in raw_decode
> raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

这个问题解决了吗？
