### ISSUE TITLE
老大依赖里还有错误

### ISSUE THREAD

**Issue by 40740** [fuckwonderfulsuccess/WCplus#4]
pip3 install webbrowser
Collecting webbrowser
  Could not find a version that satisfies the requirement webbrowser (from versions: )
No matching distribution found for webbrowser

**Comment by LuvSheRyL** [comment]
可去托管whl那边下对应python版本的whl文件。

**Comment by fuckwonderfulsuccess** [comment]
可以不用安装webbrowser, thanks
