### ISSUE TITLE
求助机器识别码被作者禁用后的解决办法

### ISSUE THREAD

**Issue by LuvSheRyL** [fuckwonderfulsuccess/WCplus#6]
本人目前已经被禁用。除了按照反编译项目继续测试外，还有其他可行思路吗？

**Comment by fuckwonderfulsuccess** [comment]
机器识别码和mac地址绑定，更换mac地址后机器识别码也会改变，需要重新生成license.ca。
p.s. 在源码中没有看到跟除微信以外的服务器通信的相关代码，不太可能是机器识别码被作者禁用。

**Comment by Automobile86** [comment]
你好，生成license.ca的程序只针对于Mac，windows不能用吗？

**Comment by fuckwonderfulsuccess** [comment]
@Automobile86 能用，我说的mac地址不是Mac。。。
